"use client";

import { useEffect } from "react";

// Compatibility for recovery links generated by the previous deployment.
// The URL fragment is only available in the browser, so preserve it while
// forwarding the user to the unified login/recovery screen.
export default function LegacyRecoveryPage() {
  useEffect(() => {
    const current = new URL(window.location.href);
    const params = new URLSearchParams(current.search);
    params.set("mode", "recovery");

    const target = `/login?${params.toString()}${window.location.hash}`;
    window.location.replace(target);
  }, []);

  return (
    <main className="loginShell">
      <div className="loginCard">
        <div className="brandMark">₸</div>
        <h1>Восстановление пароля</h1>
        <p>Открываю форму нового пароля…</p>
      </div>
    </main>
  );
}
